name: u_example
description: "Demonstrates how to use the u plugin."
publish_to: 'none'

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  u:
    path: ../
  cupertino_icons: ^1.0.9

flutter:
  uses-material-design: true
