import "package:u/utilities.dart";

import "../../demo/demo.dart";

/// UApp, UAppState and U: app, device, platform, theme and language info.
class AppPage extends StatelessWidget {
  const AppPage({super.key});

  @override
  Widget build(BuildContext context) => DemoPage(
    title: "UApp",
    intro: "Tap any row to run it. Everything here is filled by initU() in main().",
    children: <Widget>[
      DemoGroup("App", <Widget>[
        Fn("UApp.name", () => UApp.name, auto: true),
        Fn("UApp.packageName", () => UApp.packageName, auto: true),
        Fn("UApp.version", () => UApp.version, auto: true),
        Fn("UApp.buildNumber", () => UApp.buildNumber, auto: true),
        Fn("UApp.fullVersion", () => UApp.fullVersion, auto: true),
        Fn("UApp.packageInfo", () => UApp.packageInfo),
        Fn("UApp.initPackageInfo()", UApp.initPackageInfo),
        Fn("UApp.isPackageInfoReady", () => UApp.isPackageInfoReady),
        Fn("UApp.installTime", () => UApp.installTime),
        Fn("UApp.updateTime", () => UApp.updateTime),
        Fn("UApp.installer", () => UApp.installer),
        Fn("UApp.signatureSha256", () => UApp.signatureSha256, note: "Android only"),
        Fn("UApp.flavor", () => UApp.flavor),
        Fn("UApp.isDebug / isProfile / isRelease", () => <bool>[UApp.isDebug, UApp.isProfile, UApp.isRelease]),
        Fn("UApp.isFirstLaunch", () => UApp.isFirstLaunch),
        Fn("UApp.isFirstLaunchOfVersion", () => UApp.isFirstLaunchOfVersion),
        Fn("UApp.justUpdated", () => UApp.justUpdated),
        Fn("UApp.previousVersion", () => UApp.previousVersion),
        Fn("UApp.launchCount", () => UApp.launchCount),
        Fn("UApp.firstLaunchTime", () => UApp.firstLaunchTime),
        Fn("UApp.versionFirstLaunchTime", () => UApp.versionFirstLaunchTime),
        Fn('UApp.compareVersions("1.2.0", "1.10.0")', () => UApp.compareVersions("1.2.0", "1.10.0")),
        Fn('UApp.isVersionAtLeast("0.9.0")', () => UApp.isVersionAtLeast("0.9.0")),
        Fn('UApp.isVersionOlderThan("99.0.0")', () => UApp.isVersionOlderThan("99.0.0")),
      ]),
      DemoGroup("Platform", <Widget>[
        Fn("UApp.isWeb / isAndroid / isIos", () => <bool>[UApp.isWeb, UApp.isAndroid, UApp.isIos], auto: true),
        Fn("UApp.isMacOs / isWindows / isLinux / isFuchsia", () => <bool>[UApp.isMacOs, UApp.isWindows, UApp.isLinux, UApp.isFuchsia], auto: true),
        Fn("UApp.isMobile / isDesktop", () => <bool>[UApp.isMobile, UApp.isDesktop], auto: true),
        Fn("UApp.isEmbedded", () => UApp.isEmbedded, note: "Web only"),
        Fn("UApp.queryParameters", () => UApp.queryParameters, note: "Web only"),
      ]),
      DemoGroup("Screen size", <Widget>[
        Fn("UApp.isLandscape() / isPortrait()", () => <bool>[UApp.isLandscape(), UApp.isPortrait()]),
        Fn("UApp.isTablet() / isPhone()", () => <bool>[UApp.isTablet(), UApp.isPhone()]),
        Fn("UApp.isMobileSize() / isTabletSize() / isDesktopSize()", () => <bool>[UApp.isMobileSize(), UApp.isTabletSize(), UApp.isDesktopSize()]),
      ]),
      DemoGroup("Theme & language", <Widget>[
        Fn("UApp.locale()", UApp.locale, auto: true),
        Act('UApp.updateLocale(Locale("en"))', () => UApp.updateLocale(const Locale("en"))),
        Act('UApp.updateLocale(Locale("fa"))', () => UApp.updateLocale(const Locale("fa"))),
        Fn("UApp.isDarkMode / isDarkTheme()", () => <bool>[UApp.isDarkMode, UApp.isDarkTheme()]),
        Act("UApp.toDarkMode()", UApp.toDarkMode),
        Act("UApp.toLightMode()", UApp.toLightMode),
        Fn("UAppState.isDarkMode", () => UAppState.isDarkMode),
        Act("UAppState.changeThemeMode(ThemeMode.system)", () => UAppState.changeThemeMode(ThemeMode.system), note: "Not saved; UApp.toDarkMode() saves"),
        Act('UAppState.updateLocale(Locale("en"))', () => UAppState.updateLocale(const Locale("en"))),
      ]),
      DemoGroup("Device", <Widget>[
        Fn("UApp.deviceInfo", () => UApp.deviceInfo),
        Fn("UApp.isDeviceInfoReady", () => UApp.isDeviceInfoReady),
        Fn("UApp.deviceId()", UApp.deviceId, auto: true),
        Fn("UApp.deviceModel", () => UApp.deviceModel, auto: true),
        Fn("UApp.deviceManufacturer", () => UApp.deviceManufacturer),
        Fn("UApp.deviceBrand", () => UApp.deviceBrand),
        Fn("UApp.deviceName", () => UApp.deviceName),
        Fn("UApp.deviceType", () => UApp.deviceType, auto: true),
        Fn("UApp.isPhysicalDevice / isEmulator", () => <bool>[UApp.isPhysicalDevice, UApp.isEmulator]),
        Fn("UApp.isPhoneDevice / isTabletDevice / isDesktopDevice / isTvDevice", () => <bool>[UApp.isPhoneDevice, UApp.isTabletDevice, UApp.isDesktopDevice, UApp.isTvDevice]),
        Fn("UApp.osName", () => UApp.osName, auto: true),
        Fn("UApp.osVersion", () => UApp.osVersion, auto: true),
        Fn("UApp.osBuild", () => UApp.osBuild),
        Fn("UApp.sdkInt", () => UApp.sdkInt, note: "Android only"),
        Fn("UApp.cpuArch", () => UApp.cpuArch),
        Fn("UApp.cpuCores", () => UApp.cpuCores),
        Fn("UApp.totalMemory?.toBKMG()", () => UApp.totalMemory?.toBKMG()),
        Fn("UApp.timeZone", () => UApp.timeZone),
        Fn("UApp.deviceLocales", () => UApp.deviceLocales),
        Fn("UApp.is24HourFormat", () => UApp.is24HourFormat),
        Fn("UApp.deviceExtra", () => UApp.deviceExtra),
        Fn("UApp.deviceHeaders", () => UApp.deviceHeaders),
        Fn("UApp.userAgent", () => UApp.userAgent),
      ]),
      DemoGroup("Battery, memory, disk", <Widget>[
        Fn("await UApp.deviceStatus()", UApp.deviceStatus),
        Fn("await UApp.batteryLevel()", UApp.batteryLevel),
        Fn("await UApp.isCharging()", UApp.isCharging),
        Fn("await UApp.isLowBattery()", UApp.isLowBattery),
        Fn("await UApp.isPowerSaveMode()", UApp.isPowerSaveMode),
        Fn("await UApp.shouldSaveEnergy()", UApp.shouldSaveEnergy),
        Fn("(await UApp.freeDiskSpace())?.toBKMG()", () async => (await UApp.freeDiskSpace())?.toBKMG()),
        Fn("(await UApp.freeMemory())?.toBKMG()", () async => (await UApp.freeMemory())?.toBKMG()),
      ]),
      DemoGroup("Security", <Widget>[
        Fn("await UApp.deviceIntegrity()", UApp.deviceIntegrity),
        Fn("await UApp.isDeviceCompromised()", UApp.isDeviceCompromised),
        Fn("await UApp.isRooted()", UApp.isRooted),
      ]),
      DemoGroup("System UI", <Widget>[
        Act("UApp.hideKeyboard()", UApp.hideKeyboard),
        Act("UApp.haptic(UHapticType.success)", () => UApp.haptic(UHapticType.success), note: "Android / iOS"),
        Act("UApp.setStatusBarLight(true)", () => UApp.setStatusBarLight(true)),
        Act("UApp.setOrientations([portraitUp])", () => UApp.setOrientations(<DeviceOrientation>[DeviceOrientation.portraitUp])),
        Act("UApp.setOrientations([]) (unlock)", () => UApp.setOrientations(<DeviceOrientation>[])),
        Act("UApp.setFullScreen(true)", () => UApp.setFullScreen(true)),
        Act("UApp.setFullScreen(false)", () => UApp.setFullScreen(false)),
        Fn("UApp.keepScreenOn(true)", () => UApp.keepScreenOn(true)),
        Fn("UApp.keepScreenOn(false)", () => UApp.keepScreenOn(false)),
        Act("UApp.exit()", () => UNavigator.confirm(title: "Exit?", message: "Closes the app (Android, desktop).", onConfirm: UApp.exit)),
      ]),
      DemoGroup("U (app-wide data)", <Widget>[
        Fn("U.baseUrl", () => U.baseUrl, auto: true),
        Fn("U.defaultPhoneCountry.nameEn", () => U.defaultPhoneCountry.nameEn),
        Fn("U.s.save", () => U.s.save, auto: true),
        Act('U.addTab("Tab", page)', () => U.addTab("Tab ${U.tabs.length + 1}", const Center(child: Text("Tab")))),
        Act('U.addOrSwitchTab("Home", page)', () => U.addOrSwitchTab("Home", const Center(child: Text("Home")))),
        Act('U.replaceTab("Home", page)', () => U.replaceTab("Home", const Center(child: Text("Home 2")))),
        Act("U.removeTab(0)", () => U.removeTab(0)),
        Act("U.updateTabController()", U.updateTabController),
        Fn("U.tabs.length", () => U.tabs.length),
        const Demo("initU(baseUrl: …) and UMaterialApp(…) are used in main.dart", child: SizedBox.shrink()),
      ]),
    ],
  );
}
