import "package:u/utilities.dart";

/// The OSS acquirer field table, field for field from `OSSACQPackager`.
class OssAcqPackager extends IsoMsgPackager {
  OssAcqPackager() : super(_fields);

  static final List<IsoFieldPackager?> _fields = <IsoFieldPackager?>[
    /*000*/ IfbNumeric(4, "MESSAGE TYPE INDICATOR"),
    /*001*/ IfbBitmap(16, "BIT MAP"),
    /*002*/ IfbLlnum(19, "PRIMARY ACCOUNT NUMBER"),
    /*003*/ IfbNumeric(6, "PROCESSING CODE"),
    /*004*/ IfbNumeric(12, "AMOUNT, TRANSACTION"),
    /*005*/ IfbNumeric(12, "AMOUNT, SETTLEMENT"),
    /*006*/ IfbNumeric(12, "AMOUNT, CARDHOLDER BILLING"),
    /*007*/ IfbNumeric(10, "TRANSMISSION DATE AND TIME"),
    /*008*/ IfbNumeric(8, "AMOUNT, CARDHOLDER BILLING FEE"),
    /*009*/ IfbNumeric(8, "CONVERSION RATE, SETTLEMENT"),
    /*010*/ IfbNumeric(8, "CONVERSION RATE, CARDHOLDER BILLING"),
    /*011*/ IfbNumeric(6, "SYSTEM TRACE AUDIT NUMBER"),
    /*012*/ IfbNumeric(6, "TIME, LOCAL TRANSACTION"),
    /*013*/ IfbNumeric(4, "DATE, LOCAL TRANSACTION"),
    /*014*/ IfbNumeric(4, "DATE, EXPIRATION"),
    /*015*/ IfbNumeric(4, "DATE, SETTLEMENT"),
    /*016*/ IfbNumeric(4, "DATE, CONVERSION"),
    /*017*/ IfbNumeric(4, "DATE, CAPTURE"),
    /*018*/ IfbNumeric(4, "MERCHANTS TYPE"),
    /*019*/ IfbNumeric(3, "ACQUIRING INSTITUTION COUNTRY CODE"),
    /*020*/ IfbNumeric(3, "PAN EXTENDED COUNTRY CODE"),
    /*021*/ IfbNumeric(3, "FORWARDING INSTITUTION COUNTRY CODE"),
    /*022*/ IfbNumeric(3, "POINT OF SERVICE ENTRY MODE"),
    /*023*/ IfbNumeric(3, "CARD SEQUENCE NUMBER"),
    /*024*/ IfbNumeric(3, "NETWORK INTERNATIONAL IDENTIFIEER"),
    /*025*/ IfbNumeric(2, "POINT OF SERVICE CONDITION CODE"),
    /*026*/ IfbNumeric(2, "POINT OF SERVICE PIN CAPTURE CODE"),
    /*027*/ IfbNumeric(1, "AUTHORIZATION IDENTIFICATION RESP LEN"),
    /*028*/ IfbNumeric(9, "AMOUNT, TRANSACTION FEE"),
    /*029*/ IfbNumeric(9, "AMOUNT, SETTLEMENT FEE"),
    /*030*/ IfbNumeric(9, "AMOUNT, TRANSACTION PROCESSING FEE"),
    /*031*/ IfbNumeric(9, "AMOUNT, SETTLEMENT PROCESSING FEE"),
    /*032*/ IfbLlnum(11, "ACQUIRING INSTITUTION IDENT CODE"),
    /*033*/ IfbLlnum(11, "FORWARDING INSTITUTION IDENT CODE"),
    /*034*/ IfbVarChar.ll(28, "PAN EXTENDED"),
    /*035*/ IfbLlnum(37, "TRACK 2 DATA"),
    /*036*/ IfbVarChar.lll(104, "TRACK 3 DATA"),
    /*037*/ IfChar(12, "RETRIEVAL REFERENCE NUMBER"),
    /*038*/ IfChar(6, "AUTHORIZATION IDENTIFICATION RESPONSE"),
    /*039*/ IfChar(2, "RESPONSE CODE"),
    /*040*/ IfChar(3, "SERVICE RESTRICTION CODE"),
    /*041*/ IfChar(8, "CARD ACCEPTOR TERMINAL IDENTIFICACION"),
    /*042*/ IfChar(15, "CARD ACCEPTOR IDENTIFICATION CODE"),
    /*043*/ IfChar(40, "CARD ACCEPTOR NAME/LOCATION"),
    /*044*/ IfbVarChar.ll(25, "ADITIONAL RESPONSE DATA"),
    /*045*/ IfbVarChar.ll(76, "TRACK 1 DATA"),
    /*046*/ IfbVarChar.lll(999, "ADITIONAL DATA - ISO"),
    /*047*/ IfbVarChar.lll(999, "ADITIONAL DATA - NATIONAL"),
    /*048*/ IfbVarChar.lll(999, "ADITIONAL DATA - PRIVATE"),
    /*049*/ IfChar(3, "CURRENCY CODE, TRANSACTION"),
    /*050*/ IfChar(3, "CURRENCY CODE, SETTLEMENT"),
    /*051*/ IfChar(3, "CURRENCY CODE, CARDHOLDER BILLING"),
    /*052*/ IfbBinary(8, "PIN DATA"),
    /*053*/ IfbNumeric(16, "SECURITY RELATED CONTROL INFORMATION"),
    /*054*/ IfbVarChar.lll(120, "ADDITIONAL AMOUNTS"),
    /*055*/ IfbVarChar.lll(999, "ICC Data"),
    /*056*/ IfbVarChar.lll(999, "RESERVED ISO"),
    /*057*/ IfbVarChar.lll(999, "RESERVED NATIONAL"),
    /*058*/ IfbVarChar.lll(999, "RESERVED NATIONAL"),
    /*059*/ IfbVarChar.lll(999, "RESERVED NATIONAL"),
    /*060*/ IfbVarBinary.lll(999, "RESERVED PRIVATE"),
    /*061*/ IsoBinaryFieldPackager(999999, "RESERVED PRIVATE", interpreter: LiteralBinaryInterpreter.instance, prefixer: BcdPrefixer.llllll),
    /*062*/ IsoBinaryFieldPackager(9999, "RESERVED PRIVATE", interpreter: LiteralBinaryInterpreter.instance, prefixer: BcdPrefixer.llll),
    /*063*/ IfbVarBinary.lll(999, "RESERVED PRIVATE"),
    /*064*/ IfaBinary(4, "MESSAGE AUTHENTICATION CODE FIELD"),
    /*065*/ IfbBinary(1, "BITMAP, EXTENDED"),
    /*066*/ IfbNumeric(1, "SETTLEMENT CODE"),
    /*067*/ IfbNumeric(2, "EXTENDED PAYMENT CODE"),
    /*068*/ IfbNumeric(3, "RECEIVING INSTITUTION COUNTRY CODE"),
    /*069*/ IfbNumeric(3, "SETTLEMENT INSTITUTION COUNTRY CODE"),
    /*070*/ IfbNumeric(3, "NETWORK MANAGEMENT INFORMATION CODE"),
    /*071*/ IfbNumeric(4, "MESSAGE NUMBER"),
    /*072*/ IfbNumeric(4, "MESSAGE NUMBER LAST"),
    /*073*/ IfbNumeric(6, "DATE ACTION"),
    /*074*/ IfbNumeric(10, "CREDITS NUMBER"),
    /*075*/ IfbNumeric(10, "CREDITS REVERSAL NUMBER"),
    /*076*/ IfbNumeric(10, "DEBITS NUMBER"),
    /*077*/ IfbNumeric(10, "DEBITS REVERSAL NUMBER"),
    /*078*/ IfbNumeric(10, "TRANSFER NUMBER"),
    /*079*/ IfbNumeric(10, "TRANSFER REVERSAL NUMBER"),
    /*080*/ IfbNumeric(10, "INQUIRIES NUMBER"),
    /*081*/ IfbNumeric(10, "AUTHORIZATION NUMBER"),
    /*082*/ IfbNumeric(12, "CREDITS, PROCESSING FEE AMOUNT"),
    /*083*/ IfbNumeric(12, "CREDITS, TRANSACTION FEE AMOUNT"),
    /*084*/ IfbNumeric(12, "DEBITS, PROCESSING FEE AMOUNT"),
    /*085*/ IfbNumeric(12, "DEBITS, TRANSACTION FEE AMOUNT"),
    /*086*/ IfbNumeric(16, "CREDITS, AMOUNT"),
    /*087*/ IfbNumeric(16, "CREDITS, REVERSAL AMOUNT"),
    /*088*/ IfbNumeric(16, "DEBITS, AMOUNT"),
    /*089*/ IfbNumeric(16, "DEBITS, REVERSAL AMOUNT"),
    /*090*/ IfbNumeric(42, "ORIGINAL DATA ELEMENTS"),
    /*091*/ IfChar(1, "FILE UPDATE CODE"),
    /*092*/ IfChar(2, "FILE SECURITY CODE"),
    /*093*/ IfChar(6, "RESPONSE INDICATOR"),
    /*094*/ IfChar(7, "SERVICE INDICATOR"),
    /*095*/ IfChar(42, "REPLACEMENT AMOUNTS"),
    /*096*/ IfbBinary(16, "MESSAGE SECURITY CODE"),
    /*097*/ IfbNumeric(17, "AMOUNT, NET SETTLEMENT"),
    /*098*/ IfChar(25, "PAYEE"),
    /*099*/ IfbLlnum(11, "SETTLEMENT INSTITUTION IDENT CODE"),
    /*100*/ IfbLlnum(11, "RECEIVING INSTITUTION IDENT CODE"),
    /*101*/ IfbVarChar.ll(17, "FILE NAME"),
    /*102*/ IfbVarChar.ll(28, "ACCOUNT IDENTIFICATION 1"),
    /*103*/ IfbVarChar.ll(28, "ACCOUNT IDENTIFICATION 2"),
    /*104*/ IfbVarChar.lll(100, "TRANSACTION DESCRIPTION"),
    /*105*/ IfbVarChar.lll(999, "RESERVED ISO USE"),
    /*106*/ IfbVarChar.lll(999, "RESERVED ISO USE"),
    /*107*/ IfbVarChar.lll(999, "RESERVED ISO USE"),
    /*108*/ IfbVarChar.lll(999, "RESERVED ISO USE"),
    /*109*/ IfbVarChar.lll(999, "RESERVED ISO USE"),
    /*110*/ IfbVarChar.lll(999, "RESERVED ISO USE"),
    /*111*/ IfbVarChar.lll(999, "RESERVED ISO USE"),
    /*112*/ IfbVarChar.lll(999, "RESERVED NATIONAL USE"),
    /*113*/ IfbVarChar.lll(999, "RESERVED NATIONAL USE"),
    /*114*/ IfbVarChar.lll(999, "RESERVED NATIONAL USE"),
    /*115*/ IfbVarChar.lll(999, "RESERVED NATIONAL USE"),
    /*116*/ IfbVarChar.lll(999, "RESERVED NATIONAL USE"),
    /*117*/ IfbVarChar.lll(999, "RESERVED NATIONAL USE"),
    /*118*/ IfbVarChar.lll(999, "RESERVED NATIONAL USE"),
    /*119*/ IfbVarChar.lll(999, "RESERVED NATIONAL USE"),
    /*120*/ IfbVarChar.lll(999, "RESERVED PRIVATE USE"),
    /*121*/ IfbVarChar.lll(999, "RESERVED PRIVATE USE"),
    /*122*/ IfbVarChar.lll(999, "RESERVED PRIVATE USE"),
    /*123*/ IfbVarChar.lll(999, "RESERVED PRIVATE USE"),
    /*124*/ IfbVarChar.lll(999, "RESERVED PRIVATE USE"),
    /*125*/ IfbVarChar.lll(999, "RESERVED PRIVATE USE"),
    /*126*/ IfbVarChar.lll(999, "RESERVED PRIVATE USE"),
    /*127*/ IfbVarChar.lll(999, "RESERVED PRIVATE USE"),
    /*128*/ IfbBinary(8, "MAC 2"),
  ];
}
